import pandas as pd
import matplotlib.pyplot as plt

# Load the CSV generated by Go
df = pd.read_csv("simulation_output.csv")

# Quick overview
print("CSV Head:")
print(df.head())
print("\nBasic stats:")
print(df.describe())

# Compute average speed per tick (all segments)
avg_speed_per_tick = df.groupby('Tick')['AverageSpeed'].mean()

# Compute total cars per tick (all segments)
total_cars_per_tick = df.groupby('Tick')['CarCount'].sum()

# Plot average speed over time
plt.figure(figsize=(10, 5))
plt.plot(avg_speed_per_tick.index, avg_speed_per_tick.values, label="Avg Speed (m/s)")
plt.xlabel("Tick")
plt.ylabel("Average Speed (m/s)")
plt.title("Average Speed Over Time")
plt.legend()
plt.grid(True)
plt.show()

# Plot total cars over time
plt.figure(figsize=(10, 5))
plt.plot(total_cars_per_tick.index, total_cars_per_tick.values, label="Total Cars", color="orange")
plt.xlabel("Tick")
plt.ylabel("Total Cars")
plt.title("Total Cars Over Time")
plt.legend()
plt.grid(True)
plt.show()

